/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia;

import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class PnlMosPorSuc extends javax.swing.JPanel
{

    /**
     * Creates new form PnlMosPorSuc
     */
    public PnlMosPorSuc()
    {
        initComponents();
        moscom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        mostContSuc = new javax.swing.JPanel();
        mosSuc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(78, 82, 85));

        mostContSuc.setBackground(new java.awt.Color(78, 82, 85));
        mostContSuc.setLayout(new java.awt.GridLayout(0, 4, 5, 10));
        jScrollPane1.setViewportView(mostContSuc);

        mosSuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mosSuc.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                mosSucItemStateChanged(evt);
            }
        });
        mosSuc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mosSucActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mapa.png"))); // NOI18N
        jLabel1.setText("Seleccione una sucursal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mosSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mosSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mosSucActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mosSucActionPerformed
    {//GEN-HEADEREND:event_mosSucActionPerformed


    }//GEN-LAST:event_mosSucActionPerformed

    private void mosSucItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_mosSucItemStateChanged
    {//GEN-HEADEREND:event_mosSucItemStateChanged
        mostContSuc.removeAll();
        if (IntrPrincipal.getSuc().size()>0)
        {
            most();
        }
        mostContSuc.revalidate();
        mostContSuc.repaint();
    }//GEN-LAST:event_mosSucItemStateChanged

    private void moscom()
    {
        for (int i = 0; i < IntrPrincipal.getSuc().size(); i++)
        {
            mosSuc.addItem(IntrPrincipal.getSuc().get(i));
        }
    }

    private void most()
    {
        for (int j = 0; j < IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).size(); j++)
        {
            if (IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j) instanceof Pintura)
            {
                JLabel lab = new JLabel("<html>Placas: <p>" + ((Auto) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getPlacas()
                        + "<p>Modelo: <p>" + ((Auto) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getModelo()
                        + "<p>Año:<p>" + ((Auto) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getAnio()
                        + "<p>Color:<p>" + ((Pintura) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getColor()
                        + "<p>Fecha de ingreso:<p>" + ((Pintura) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getFechaIngreso()
                        + "<p>Fecha de salida:<p>" + ((Pintura) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getFechaSalida()
                        + "<html>", new javax.swing.ImageIcon(getClass().getResource("/imagenes/icnPin.png")),
                        javax.swing.SwingConstants.CENTER);
                //lab.setSize(200, 200);
                lab.setBackground(new java.awt.Color(226, 222, 219));
                lab.setOpaque(true);
                lab.setFont(new java.awt.Font("Tahoma", 1, 12));
                mostContSuc.add(lab);
            } else
            {
                JLabel lab = new JLabel("<html>Sucursal:<p>" + IntrPrincipal.getSuc().get(mosSuc.getSelectedIndex())
                        + "<p>Placas:<p>" + ((Auto) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getPlacas()
                        + "<p>Modelo:<p>" + ((Auto) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getModelo()
                        + "<p>Año:<p>" + ((Auto) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getAnio()
                        + "<p>Presupuesto:<p>" + ((Servicio) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getPresupuesto()
                        + "<p>Tip. de servicio:<p>" + ((Servicio) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getTipoServicio()
                        + "<p>Pagado:<p>" + ((Servicio) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getPagado()[0]
                        + ((Servicio) IntrPrincipal.getAut().get(mosSuc.getSelectedIndex()).get(j)).getPagado()[1] + "<html>",
                        new javax.swing.ImageIcon(getClass().getResource("/imagenes/icnRep.png")),
                        javax.swing.SwingConstants.CENTER);
                //lab.setSize(200, 200);
                lab.setBackground(new java.awt.Color(226, 222, 219));
                lab.setFont(new java.awt.Font("Tahoma", 1, 12));
                lab.setOpaque(true);
                mostContSuc.add(lab);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mosSuc;
    private javax.swing.JPanel mostContSuc;
    // End of variables declaration//GEN-END:variables
}
